import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TAC Official Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} 
          min-h-svh flex flex-col 
          bg-background text-foreground font-sans antialiased
          selection:bg-primary/20 selection:text-primary
        `}
      >
        <Header />
        {/* flex-1 lets main take up the remaining viewport space pushing footers down */}
        <main className="flex flex-1 flex-col">{children}</main>

        <Toaster />
      </body>
    </html>
  );
}
